# Netlify config for this repo
[build]
  command = "npm run build"
  publish = "viteproject/dist"

[build.environment]
  NODE_VERSION = "20"

# SPA fallback (keeps client-side routing working)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200